services:
  - docker
before_install:
  - docker build -t kpfromer/movie-chooser .
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kpfromer/movie-chooser
